# Metadata for the site header and footer
title: OCP CI Onboarding
description: Documentation for OCP CI Onboarding written by CSPI-QE

# Set the production website URL when previewing
baseurl: "/cspi-qe.github.io"


remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
